-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.clientes
(
    id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(10) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(80) COLLATE pg_catalog."default",
    "FK_Nit" character varying(12) COLLATE pg_catalog."default",
    CONSTRAINT cliente_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.detalle_facturas
(
    nrofact character varying(10) COLLATE pg_catalog."default" NOT NULL,
    nroprod character varying(5) COLLATE pg_catalog."default" NOT NULL,
    cantidad integer,
    precio double precision,
    CONSTRAINT detalle_facturas_pkey PRIMARY KEY (nrofact, nroprod)
);

CREATE TABLE IF NOT EXISTS public.empresas
(
    nit character varying(12) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "telefono " character varying(10) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(80) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT empresas_pkey PRIMARY KEY (nit)
);

CREATE TABLE IF NOT EXISTS public.facturas
(
    nrofact character varying(10) COLLATE pg_catalog."default" NOT NULL,
    idcliente character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT facturas_pkey PRIMARY KEY (nrofact)
);

CREATE TABLE IF NOT EXISTS public.productos
(
    id character varying(5) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    marca character varying(50) COLLATE pg_catalog."default" NOT NULL,
    cantidad numeric(10, 0) NOT NULL,
    precio numeric(10, 0) NOT NULL,
    CONSTRAINT productos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.proveedor_productos
(
    id character varying(5) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT proveedor_productos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.proveedores
(
    id character varying(5) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(80) COLLATE pg_catalog."default" NOT NULL,
    telefono numeric(10, 0) NOT NULL,
    empresa character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT proveedores_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.clientes
    ADD CONSTRAINT "FK_Nit" FOREIGN KEY ("FK_Nit")
    REFERENCES public.empresas (nit) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.detalle_facturas
    ADD CONSTRAINT fkdetprod FOREIGN KEY (nroprod)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.detalle_facturas
    ADD CONSTRAINT fkfactdet FOREIGN KEY (nrofact)
    REFERENCES public.facturas (nrofact) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.facturas
    ADD CONSTRAINT factcli FOREIGN KEY (idcliente)
    REFERENCES public.clientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;